### ISSUE TITLE
State equation of model 

### ISSUE THREAD

**Issue by taminhtoan2601** [Intelligent-Quads/iq_tutorials#11]
Hello, 

I have a question in need of your help. Actually, I dont understand the state equations of drone that you wrote in gnc_function.hpp, do you have any document to talk about these equations? Because I really need it to be able to write the controller... Thank you so much in advance !!!

**Comment by ericjohnson97** [comment]
I actually don't really have too much documentation on the iq_gnc functions. I have been wanting to do youtube videos on making the gnc functions from scratch, but I have been kicking the can down the road for over a year now. Here is a presentation I made to help explain the functions that are in the gnc_functions my senior year when I was planning on graduating and young members of Texas Aerial Robotics were inheriting the code. Hope this is at least a little helpful.

https://docs.google.com/presentation/d/1FcJk4tGGB6bQw4Z1YCBW5zZd8FRKhd-AAdej0Bnkars/edit?usp=sharing
