### ISSUE TITLE
Failed to update submodule

### ISSUE THREAD

**Issue by i-m-abbhay** [Intelligent-Quads/iq_tutorials#36]
I am unable to run "git submodule update --init --recursive"

**Comment by krum-cck** [comment]
Hi, I am having the same issue updating submodules. It appears that the cause is Github stopped the usage of URL starting with 'git://'. Did you solve it ?

**Comment by i-m-abbhay** [comment]
No not till now. I thought there's some issue with my OS. I have already tried reinstalling Ubuntu on my machine but still getting same error.

**Comment by MarsJ48** [comment]
Any updates guys?

**Comment by i-m-abbhay** [comment]
No, Still struggling to figure it out... I got busy in my academics due to Endsemester Exams.

**Comment by French-isotope** [comment]
Hi @i-m-abbhay @krum-cck @MarsJ48 , I get the same error and it appears that using : 

`git config --global url."https://".insteadOf git://`

had done some good at my side, until I change that nothing was working. (I'm still into troubles after this step by the way) but let me know if it was good for you.

**Comment by French-isotope** [comment]
Hi @i-m-abbhay @krum-cck @MarsJ48

You could try to use 

`git checkout Copter-4.1.5`

and then : 

`git submodule update --init --recursive` it should be good, let me know if not.

**Comment by rabah1991** [comment]
Hi, for me i solved it on Ubuntu 20.04 by using the **latest copter version** instead of **4.0.4**
 It would be as follow:

`git checkout Copter-4.2`

and then :
`
git submodule update --init --recursive`
