### ISSUE TITLE
avoidance.cpp

### ISSUE THREAD

**Issue by debanik123** [Intelligent-Quads/iq_tutorials#6]
error: ‘get_current_loaction’ was not declared in this scope

**Comment by ericjohnson97** [comment]
I added that functionality relatively recently, so if you have had iq_gnc cloned for a while, that funtion does not exist in the gnc functions header file

https://github.com/Intelligent-Quads/iq_gnc/blob/master/include/gnc_functions.hpp

try doing a git pull in your iq_gnc folder

**Comment by debanik123** [comment]
Sir, I have done it

**Comment by debanik123** [comment]
and do catkin_make

**Comment by pratik-a99** [comment]
> error: ‘get_current_loaction’ was not declared in this scope

I think this should be "get_current_location"

**Comment by ericjohnson97** [comment]
ah! yes. I fixed that at some point, cause I originally fat fingered my keyboard and really messed up my programs by using copy paste and auto complete. it definitely should work if you call it using `get_current_location`. Big up @pratik-a99

**Comment by debanik123** [comment]
Thanks now it is working

**Comment by debanik123** [comment]
Can you make video on in auto mode obstacle avoidance using silt gazebo
