### ISSUE TITLE
 error: ‘set_mode’ was not declared in this scope

### ISSUE THREAD

**Issue by ans-qureshi** [Intelligent-Quads/iq_tutorials#9]
Hi!
I was following the tutorial "Drone Swarms with Ardupilot+MAVROS" and as suggested used set_mode() function to set mode to guided in multi_drone.cpp and got this error:

```
/home/ans/catkin_ws/src/iq_gnc/src/multi_square.cpp:20:2: error: ‘set_mode’ was not declared in this scope  set_mode("GUIDED");
  ^~~~~~~~
/home/ans/catkin_ws/src/iq_gnc/src/multi_square.cpp:20:2: note: suggested alternative: ‘gnc_node’
  `set_mode("GUIDED");
```
Need some help @ericjohnson97  :/

**Comment by ericjohnson97** [comment]
oh haha. That tutorial was still in development. Completed the tutorial today. git pull for the latest iq_gnc and iq_sim. should be fixed now,

**Comment by ans-qureshi** [comment]
Yup, Got fixed :+1: :)
